"""Audit Azure Kinect trials and estimate a documented segment-mass CoM proxy.

Invoked by run_audit.py; plotting can be regenerated by make_evidence.py.
No raw rescaling, force inference, floor inference, or synthetic fall generation.
"""
from pathlib import Path
import argparse, csv, hashlib, io, json, re, zipfile
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

ROOT = Path(__file__).resolve().parents[1]
NAMES = ['pelvis','spine_navel','spine_chest','neck','clavicle_left','shoulder_left',
         'elbow_left','wrist_left','hand_left','handtip_left','thumb_left','clavicle_right',
         'shoulder_right','elbow_right','wrist_right','hand_right','handtip_right','thumb_right',
         'hip_left','knee_left','ankle_left','foot_left','hip_right','knee_right','ankle_right',
         'foot_right','head','nose','eye_left','ear_left','eye_right','ear_right']
PARENTS = [-1,0,1,2,2,4,5,6,7,8,7,2,11,12,13,14,15,14,0,18,19,20,0,22,23,24,3,26,26,26,26,26]
LIMBS = {'upper_arm_left':(5,6),'forearm_left':(6,7),'upper_arm_right':(12,13),
         'forearm_right':(13,14),'thigh_left':(18,19),'shank_left':(19,20),
         'thigh_right':(22,23),'shank_right':(23,24)}
LEFT={4,5,6,7,8,9,10,18,19,20,21}
RIGHT={11,12,13,14,15,16,17,22,23,24,25}
COLORS=['#176D8A','#D07326','#6774AD','#24865D','#A14568']
SOURCES = {
 'joints':'https://learn.microsoft.com/en-us/previous-versions/azure/kinect-dk/body-joints',
 'axes':'https://learn.microsoft.com/en-us/previous-versions/azure/kinect-dk/coordinate-systems',
 'parameters':'https://www.has-motion.com/wiki/doku.php?id=visual3d:documentation:definitions:adjusted_zatsiorsky-seluyanov_s_segment_inertia_parameters',
 'paper':'https://doi.org/10.1016/0021-9290(95)00178-6'
}

def dump(path, value):
    path.write_text(json.dumps(value,indent=2,allow_nan=False)+'\n')

def write_csv(path, rows):
    if not rows: return
    fields=list(dict.fromkeys(k for r in rows for k in r))
    with path.open('w',newline='') as f:
        w=csv.DictWriter(f,fieldnames=fields);w.writeheader();w.writerows(rows)

def segment_model():
    # Male mass fractions and proximal fractions as listed in the cited Visual3D
    # implementation table. HEAD, HAND, FOOT and NECK are SDK landmark proxies.
    # The shank fraction in that table is 0.4395; other implementations use
    # 0.4459. This difference is explicitly quantified, not silently reconciled.
    s=[dict(name='head',mass_fraction=.0694,a=[26],b=[26],fraction=0.,
            mapping='SDK HEAD point proxy; no vertex/neck anatomical head segment'),
       dict(name='trunk',mass_fraction=.4346,a=[3],b=[18,22],fraction=.5138,
            mapping='NECK to midpoint(HIP_LEFT,HIP_RIGHT); NECK approximates proximal trunk landmark')]
    for side,upper,fore,hand,thigh,shank,foot in [
        ('left',(5,6),(6,7),8,(18,19),(19,20),(20,21)),
        ('right',(12,13),(13,14),15,(22,23),(23,24),(24,25))]:
        for name,pair,mass,fraction in [('upper_arm',upper,.0271,.5772),('forearm',fore,.0162,.4574),
                                       ('thigh',thigh,.1416,.4095),('shank',shank,.0433,.4395)]:
            s.append(dict(name=f'{name}_{side}',mass_fraction=mass,a=[pair[0]],b=[pair[1]],
                          fraction=fraction,mapping='SDK joint centers approximate anatomical endpoints'))
        s.append(dict(name='hand_'+side,mass_fraction=.0061,a=[hand],b=[hand],fraction=0.,
                      mapping='SDK HAND point proxy, not published wrist-to-finger CoM fraction'))
        s.append(dict(name='foot_'+side,mass_fraction=.0137,a=[foot[0]],b=[foot[1]],fraction=.5,
                      mapping='ANKLE/FOOT midpoint proxy; heel and toe landmarks unavailable'))
    return s

def com_proxy(x,segments):
    positions=np.stack([(1-s['fraction'])*x[:,s['a']].mean(1)+s['fraction']*x[:,s['b']].mean(1)
                        for s in segments],1)
    weights=np.array([s['mass_fraction'] for s in segments])
    return (positions*weights[None,:,None]).sum(1),positions

def sensitivity(x,segments,base):
    variants={}
    # Alternative landmark mappings, not confidence intervals or accuracy bounds.
    q=[dict(s) for s in segments];q[1]['a']=[5,12]
    variants['trunk_shoulder_midpoint']=com_proxy(x,q)[0]
    q=[dict(s) for s in segments];q[0].update(a=[3],b=[26],fraction=.5)
    variants['head_neck_midpoint']=com_proxy(x,q)[0]
    q=[dict(s) for s in segments]
    for s in q:
        if s['name'].startswith('foot'): s['fraction']=1.
    variants['foot_point']=com_proxy(x,q)[0]
    q=[dict(s) for s in segments]
    for s in q:
        if s['name'].startswith('shank'): s['fraction']=.4459
    variants['shank_fraction_0p4459']=com_proxy(x,q)[0]
    return {k:float(np.linalg.norm(v-base,axis=1).max()) for k,v in variants.items()}

def analyze(input_path, cfg, root):
    rawdir=root/'raw';out=root/'results';plots=out/'plots';comdir=out/'com'
    for d in [rawdir,out,plots,comdir]:d.mkdir(parents=True,exist_ok=True)
    mass=cfg['mass_lb']*.45359237;height=cfg['height_in']*.0254;fps=cfg['fps']
    segments=segment_model()
    if cfg['sex'] != 'male':
        raise ValueError('This documented model supports adult male coefficients only; supply a reviewed model before other populations.')
    assert np.isclose(sum(s['mass_fraction'] for s in segments),1,atol=1e-12)
    for s in segments:s['mass_kg']=mass*s['mass_fraction']
    dump(root/'segment_model.json',{'status':'Approximate segment-mass CoM proxy, not validated anatomical CoM',
         'mass_kg':mass,'height_m':height,'source':SOURCES,'segments':segments,
         'height_use':'Reported stature is retained for diagnostic ratios only. No eye-to-foot or per-frame rescaling.',
         'parameter_note':'Shank coefficient follows Visual3D table (0.4395); 0.4459 variant is quantified separately.'})
    write_csv(out/'segment_mass_model.csv',[{**s,'a':','.join(NAMES[j] for j in s['a']),
                                            'b':','.join(NAMES[j] for j in s['b'])} for s in segments])
    manifest=[];stats=[];bone_stats=[];events=[];frames=[];dataset={};coms={};lengths={};scales={};sens=[]
    pattern=re.compile(r'(?P<subject>S\d+)(?P<activity>A\d+)(?P<trial>T\d+)\.csv',re.I)
    if input_path.is_dir():
        entries=[(str(p.relative_to(input_path)),p.read_bytes()) for p in sorted(input_path.rglob('*.csv'))]
    else:
        with zipfile.ZipFile(input_path) as z:
            entries=[(i.filename,z.read(i)) for i in z.infolist() if not i.is_dir() and i.filename.lower().endswith('.csv')]
    seen=set()
    ignored=[]
    for member,raw in entries:
            name=Path(member).name;match=pattern.fullmatch(name)
            if '__MACOSX' in Path(member).parts or not match or match['subject'].upper()!=cfg['subject_id']:
                ignored.append(member);continue
            name=name.upper().replace('.CSV','.csv')
            if name in seen:raise ValueError('Duplicate trial filename: '+name)
            seen.add(name);trial=Path(name).stem;act=match['activity'].upper()
            cfg['activities'].setdefault(act,act)
            (rawdir/name).write_bytes(raw)
            meta={'trial':trial,'activity':act,'description':cfg['activities'][act],
                  'bytes':len(raw),'sha256':hashlib.sha256(raw).hexdigest(),
                  'source_member':member,'status':'empty' if not raw.strip() else 'numeric'}
            manifest.append(meta)
            if meta['status']=='empty':
                stats.append({**meta,'frames':0,'first_to_last_s':None});continue
            try:
                a=np.loadtxt(io.BytesIO(raw),delimiter=',',ndmin=2)
                if a.shape[1]!=96 or len(a)<2:raise ValueError(f'Expected at least two frames and 96 columns, got {a.shape}')
                if not np.isfinite(a).all():raise ValueError('Nonfinite values: entire trial withheld, raw retained')
                check=a.reshape(-1,32,3)
                if any(np.any(np.linalg.norm(check[:,i]-check[:,j],axis=1)<=0) for i,j in LIMBS.values()):
                    raise ValueError('Zero-length limb: scale diagnostics undefined, raw retained')
                if np.any(np.linalg.norm(check[:,26]-check[:,[20,24]].mean(1),axis=1)==0):
                    raise ValueError('Zero head-to-ankle vector: orientation undefined, raw retained')
            except ValueError as error:
                meta.update(status='invalid',error=str(error));stats.append({**meta,'frames':0});continue
            x=a.reshape(-1,32,3)*{'mm':.001,'m':1.}[cfg['coordinate_units']];n=len(x);dataset[trial]=x;t=np.arange(n)/fps
            c,segment_positions=com_proxy(x,segments);coms[trial]=c
            le=np.stack([np.linalg.norm(x[:,a]-x[:,b],axis=1) for a,b in LIMBS.values()],1)
            ratios=le/np.median(le,axis=0);scale=np.median(ratios,axis=1)
            lengths[trial]=le;scales[trial]=scale
            d=np.linalg.norm(np.diff(x,axis=0),axis=2);dc=np.linalg.norm(np.diff(c,axis=0),axis=1)
            scale_step=np.r_[np.nan,np.abs(np.diff(scale)/scale[:-1])]
            joint_step=np.r_[np.nan,d.max(1)]
            flagged=(joint_step>cfg['screening']['joint_step_m'])|(scale_step>cfg['screening']['frame_scale_change_fraction'])
            head_ankle=x[:,26]-(x[:,20]+x[:,24])/2
            angle=np.degrees(np.arccos(np.clip(-head_ankle[:,1]/np.linalg.norm(head_ankle,axis=1),-1,1)))
            # Euclidean eye-to-foot spans are pose-dependent and omit head/sole offsets.
            eyes=x[:,[28,30]].mean(1)
            eyefoot=np.stack([np.linalg.norm(eyes-x[:,j],axis=1) for j in [21,25]],1).max(1)
            eq=x.mean(1);eqdiff=np.linalg.norm(c-eq,axis=1)
            corr=float(np.corrcoef(le.T)[np.triu_indices(8,1)].min()) if np.all(le.std(0)>1e-12) else None
            largest=np.unravel_index(d.argmax(),d.shape)
            stat={**meta,'frames':n,'columns':96,'first_to_last_s':(n-1)/fps,'n_over_fps_s':n/fps,
                  'nonfinite_values':int((~np.isfinite(a)).sum()),'zero_values':int((a==0).sum()),
                  'exact_duplicate_rows':n-len(np.unique(a,axis=0)),
                  'max_joint_step_m':float(d.max()),'max_joint_step_joint':NAMES[largest[1]],
                  'max_step_from_frame0':int(largest[0]),'max_step_to_frame0':int(largest[0]+1),
                  'max_pelvis_step_m':float(d[:,0].max()),'max_com_step_m':float(dc.max()),
                  'steps_any_joint_over_threshold':int((d.max(1)>cfg['screening']['joint_step_m']).sum()),'flagged_destination_frames':int(flagged.sum()),
                  'limb_scale_range_pct':float(100*(scale.max()/scale.min()-1)),
                  'max_limb_cv_pct':float((100*le.std(0)/le.mean(0)).max()),
                  'min_limb_correlation':corr,'max_normalized_limb_spread':float(np.ptp(ratios,axis=1).max()),
                  'head_ankle_angle_to_camera_minus_y_start_deg':float(angle[0]),
                  'head_ankle_angle_to_camera_minus_y_end_deg':float(angle[-1]),
                  'head_ankle_angle_min_deg':float(angle.min()),
                  'eye_foot_distance_start_m':float(eyefoot[0]),'eye_foot_distance_max_m':float(eyefoot.max()),
                  'max_eye_foot_over_reported_stature':float(eyefoot.max()/height),
                  'com_minus_equal_joint_centroid_median_m':float(np.median(eqdiff)),
                  'com_minus_equal_joint_centroid_max_m':float(eqdiff.max()),
                  'com_camera_x_range_m':float(np.ptp(c[:,0])),'com_camera_y_range_m':float(np.ptp(c[:,1])),
                  'com_camera_z_range_m':float(np.ptp(c[:,2])),
                  'com_camera_minus_y_change_end_m':float(-(c[-1,1]-c[0,1]))}
            stats.append(stat)
            sens.append({'trial':trial,**sensitivity(x,segments,c)})
            for j,name in enumerate(LIMBS):
                v=le[:,j];bone_stats.append({'trial':trial,'segment':name,'median_m':float(np.median(v)),
                      'min_m':float(v.min()),'max_m':float(v.max()),'cv_pct':float(100*v.std()/v.mean())})
            cr=[]
            for k in range(n):
                rr={'trial':trial,'activity':act,'frame0':k,'time_from_clip_start_nominal_s':k/fps,
                    'com_proxy_camera_x_m':float(c[k,0]),'com_proxy_camera_y_m':float(c[k,1]),'com_proxy_camera_z_m':float(c[k,2]),
                    'delta_camera_x_m':float(c[k,0]-c[0,0]),'delta_camera_minus_y_m':float(-c[k,1]+c[0,1]),
                    'delta_camera_z_m':float(c[k,2]-c[0,2]),'absolute_height_above_floor_m':None,
                    'true_horizontal_1_m':None,'true_horizontal_2_m':None,
                    'equal_joint_centroid_x_m':float(eq[k,0]),'equal_joint_centroid_y_m':float(eq[k,1]),
                    'equal_joint_centroid_z_m':float(eq[k,2]),'median_normalized_limb_scale':float(scale[k]),
                    'max_joint_step_from_previous_m':None if k==0 else float(joint_step[k]),
                    'review_flag':bool(flagged[k]),'head_ankle_angle_to_camera_minus_y_deg':float(angle[k]),
                    'eye_to_furthest_foot_m':float(eyefoot[k])}
                cr.append(rr);frames.append(rr)
                if flagged[k]:
                    j=int(d[k-1].argmax());events.append({'trial':trial,'from_frame0':k-1,'to_frame0':k,
                        'max_joint':NAMES[j],'max_joint_step_m':float(joint_step[k]),
                        'com_step_m':float(dc[k-1]),'limb_scale_step_fraction':float(scale_step[k]),
                        'reason':f"joint step >{cfg['screening']['joint_step_m']}m and/or scale change >{100*cfg['screening']['frame_scale_change_fraction']}%; review only"})
            write_csv(comdir/(trial+'_com_proxy.csv'),cr)
    for act, trials in cfg.get('expected_trials',{}).items():
        for tr in trials:
            trial=cfg['subject_id']+act+tr
            if trial+'.csv' not in seen:
                meta={'trial':trial,'activity':act,'description':cfg['activities'].get(act,act),'status':'missing','bytes':None,'sha256':None}
                manifest.append(meta);stats.append({**meta,'frames':0})
    dump(out/'ignored_members.json',ignored)
    cross=[]
    names=list(dataset)
    for i,a in enumerate(names):
        aa={r.tobytes() for r in dataset[a]}
        for b in names[i+1:]:
            shared=len(aa&{r.tobytes() for r in dataset[b]})
            if shared:cross.append({'trial_a':a,'trial_b':b,'exact_shared_frames':shared})
    for name,rows in [('trial_summary',stats),('manifest',manifest),('segment_lengths',bone_stats),
                      ('review_events',events),('com_proxy_all_frames',frames),('landmark_sensitivity',sens)]:
        write_csv(out/(name+'.csv'),rows);dump(out/(name+'.json'),rows)
    dump(out/'cross_trial_duplicates.json',cross)
    valid=[r for r in stats if r['frames']]
    class_summary=[]
    for act,label in cfg['activities'].items():
        vs=[r for r in valid if r['activity']==act]
        class_summary.append({'activity':act,'description':label,'expected':len(cfg.get('expected_trials',{}).get(act,[])) or None,'nonempty':len(vs),
            'unavailable_trials':[r['trial'] for r in stats if r['activity']==act and not r['frames']],
            'frames':sum(r['frames'] for r in vs),'min_span_s':min((r['first_to_last_s'] for r in vs),default=None),
            'max_span_s':max((r['first_to_last_s'] for r in vs),default=None),
            'max_scale_range_pct':max((r['limb_scale_range_pct'] for r in vs),default=None)})
    dump(out/'class_summary.json',class_summary);write_csv(out/'class_summary.csv',class_summary)
    summary={'subject':cfg,'mass_kg':mass,'height_m':height,'archive_sha256':hashlib.sha256(input_path.read_bytes()).hexdigest() if input_path.is_file() else None,
        'expected_files':sum(map(len,cfg.get('expected_trials',{}).values())) or None,'nonempty_files':len(valid),'empty_files':sum(r['status']=='empty' for r in manifest),'invalid_files':sum(r['status']=='invalid' for r in manifest),'missing_files':sum(r['status']=='missing' for r in manifest),'total_frames':len(frames),
        'first_to_last_span_min_s':min((r['first_to_last_s'] for r in valid if r['first_to_last_s'] is not None),default=None),
        'first_to_last_span_max_s':max((r['first_to_last_s'] for r in valid if r['first_to_last_s'] is not None),default=None),
        'clips_under_one_second':sum(r['first_to_last_s']<cfg['screening']['short_clip_seconds'] for r in valid),
        'clips_start_angle_over_60deg':sum(r['head_ankle_angle_to_camera_minus_y_start_deg']>60 for r in valid),
        'clips_with_review_flags':sum(r['flagged_destination_frames']>0 for r in valid),
        'total_review_flagged_destination_frames':sum(r['flagged_destination_frames'] for r in valid),
        'global_limb_scale_range_pct_min':min((r['limb_scale_range_pct'] for r in valid if r['limb_scale_range_pct'] is not None),default=None),
        'global_limb_scale_range_pct_max':max((r['limb_scale_range_pct'] for r in valid if r['limb_scale_range_pct'] is not None),default=None),
        'global_max_joint_step_m':max((r['max_joint_step_m'] for r in valid if r['max_joint_step_m'] is not None),default=None),
        'global_min_limb_correlation':min((r['min_limb_correlation'] for r in valid if r['min_limb_correlation'] is not None),default=None),
        'nonfinite_values':sum(r['nonfinite_values'] for r in valid),
        'duplicate_rows_within':sum(r['exact_duplicate_rows'] for r in valid),
        'cross_trial_duplicate_pairs':cross,
        'equal_joint_centroid_difference_median_m':float(np.median(np.concatenate([np.linalg.norm(coms[k]-dataset[k].mean(1),axis=1) for k in names]))) if names else None,
        'anatomical_com_status':'Approximate segment-mass proxy only; landmark and tracking errors uncalibrated.',
        'floor_height_status':'Unavailable. Camera axes and displacement proxies are exported instead.',
        'training_status':'No PINN trained, no synthetic falls generated. All files inspected for quality only.',
        'sources':SOURCES}
    dump(out/'study_summary.json',summary)
    dump(root/'config.json',cfg)
    return summary
def make_plots(cfg,data,coms,scales,stats,out):
    plt.rcParams.update({'font.family':'DejaVu Sans','font.size':10,'axes.spines.top':False,'axes.spines.right':False})
    fps=cfg['fps']
    # Every available frame appears in these traces. No time normalization or alignment to inferred onset.
    fig,axes=plt.subplots(max(1,len(cfg['activities'])),3,squeeze=False,figsize=(14,max(4,3*len(cfg['activities']))),layout='constrained')
    for row,(act,label) in enumerate(cfg['activities'].items()):
        trials=[k for k in data if re.search(r'A\d+',k)[0]==act]
        for trial in trials:
            c=coms[trial];delta=c-c[0];delta[:,1]*=-1;t=np.arange(len(c))/fps
            for j in range(3):axes[row,j].plot(t,delta[:,j],lw=1.5,color=COLORS[(int(re.search(r'T(\d+)',trial)[1])-1)%len(COLORS)],label=trial[-3:])
        for col,title in enumerate(['Camera X displacement','Camera -Y displacement','Camera Z displacement']):
            ax=axes[row,col];ax.axhline(0,color='#AAB6BC',lw=.5);ax.grid(alpha=.2)
            ax.set(xlabel='Seconds from clip start (nominal)',ylabel='CoM proxy displacement (m)')
            if row==0:ax.set_title(title,pad=30,fontweight='bold')
            if col==0:ax.text(0,1.04,f'{act} {label} ({len(trials)} trials)',transform=ax.transAxes,fontweight='bold')
            ax.legend(ncol=max(1,min(5,len(trials))),fontsize=8,loc='best')
    fig.suptitle(f"{cfg['subject_id']} real recordings: segment-mass CoM proxy\nCamera axes only; no floor calibration or synthetic data",fontsize=17)
    fig.savefig(out/'real_CoM_comparison.png',dpi=140);plt.close(fig)
    fig,axes=plt.subplots(max(1,len(cfg['activities'])),2,squeeze=False,figsize=(12,max(4,2.8*len(cfg['activities']))),layout='constrained')
    for row,(act,label) in enumerate(cfg['activities'].items()):
        for trial,x in data.items():
            if re.search(r'A\d+',trial)[0]!=act:continue
            t=np.arange(len(x))/fps;color=COLORS[(int(re.search(r'T(\d+)',trial)[1])-1)%len(COLORS)]
            axes[row,0].plot(t,scales[trial],color=color,label=trial[-3:])
            axes[row,1].plot(t[1:],np.linalg.norm(np.diff(x,axis=0),axis=2).max(1),color=color,label=trial[-3:])
        axes[row,0].set(title=f'{act} {label}',ylabel='Median limb length / trial median',xlabel='Nominal seconds')
        axes[row,1].set(ylabel='Largest adjacent-frame joint step (m)',xlabel='Nominal seconds')
        axes[row,1].axhline(cfg['screening']['joint_step_m'],color='#555',ls='--',lw=.7)
        for ax in axes[row]:ax.grid(alpha=.2);ax.legend(ncol=5,fontsize=8)
    fig.suptitle(f"{cfg['subject_id']} tracking diagnostics\nDashed line: configured review threshold, not a physical limit",fontsize=16)
    fig.savefig(out/'tracking_diagnostics.png',dpi=130);plt.close(fig)
    for act,label in cfg['activities'].items():
        trials=[k for k in data if re.search(r'A\d+',k)[0]==act]
        if not trials:continue
        fig,axes=plt.subplots(len(trials),4,figsize=(14,3.1*len(trials)),squeeze=False,layout='constrained')
        for row,trial in enumerate(trials):
            x=data[trial];c=coms[trial]
            # Fixed origin for a trial; never center each frame independently.
            offset=x[0,0];q=x-offset;qc=c-offset
            low=np.array([q[:,:,0].min(),(-q[:,:,1]).min()]);high=np.array([q[:,:,0].max(),(-q[:,:,1]).max()])
            middle=(low+high)/2;rad=max(high-low)/2+.10
            for col,k in enumerate(np.linspace(0,len(x)-1,4,dtype=int)):
                ax=axes[row,col]
                for j,parent in enumerate(PARENTS):
                    if parent<0:continue
                    ids=[parent,j];color='#176D8A' if j in LEFT else '#D07326' if j in RIGHT else '#354955'
                    ax.plot(q[k,ids,0],-q[k,ids,1],color=color,lw=1.3)
                ax.scatter(qc[k,0],-qc[k,1],s=28,color='#BC2543',zorder=5)
                ax.set(xlim=(middle[0]-rad,middle[0]+rad),ylim=(middle[1]-rad,middle[1]+rad),aspect='equal',
                       title=f'{trial[-3:]} · f{k} · {k/fps:.2f} s',xlabel='Camera X (m)',ylabel='Camera -Y (m)')
                ax.grid(alpha=.15)
        fig.suptitle(f'{act} {label}: observed poses and CoM proxy (red)\nFixed trial origin; camera projection only, no inferred floor',fontsize=15)
        fig.savefig(out/(act+'_skeleton_snapshots.png'),dpi=120);plt.close(fig)


